### ISSUE TITLE
arturo_z30

### ISSUE THREAD

**Issue by Arturoz30** [Fermat-ORG/competition#1]

**Comment by Luis-Fernando-Molina** [comment]
Hola Arturo, alguna pregunta?

**Comment by Luis-Fernando-Molina** [comment]
Buen día,

Hoy lunes 11 de enero a las 19hs (hora de Argentina) vamos a tener un evento en hangouts para explicar detalles sobre el concurso de Dubai y responder preguntas de los que estén interesados en participar.

Este es el link del evento:

https://plus.google.com/events/c90ku1udu7dhbc5dk8hltqj5no8

Si lo querés ver directamente en youtube (durante o después de que ocurra):

http://www.youtube.com/watch?v=kAgg-ZIOKK4

Si no podés asistir no te preocupés vamos a repetirlo en breve para que todos puedan aclarar sus dudas.

Los eventos de hangouts tienen un límite respecto a la cantidad de personas que pueden entrar y hablar. Si se llena, vamos a tratar de que los que ya hayan preguntado sigan viendolo por youtube. De todas maneras me van a poder hacer preguntas en línea por twitter a @Luis_Fer_Molina y se las respondo durante el evento.

Saludos

**Comment by gustl-arg** [comment]
@Arturoz30 Buenos dias! Te escribo para presentarte a Romulo @rjgroenke que esta manejando la competencia a partir de ahora, para ver si necesitas ayuda para completar los pasos e inscribirte.
Saludos!

**Comment by gustl-arg** [comment]
@Arturoz30 
Mi nombre es Romulo Groenke y estoy a cargo de la competencia para programadores "Adoptá un componente y viajá a Dubai".

El próximo lunes 15-2-2016 a las 19 Hs ARG ( GMT-3) 
realizamos otro hang-out de bienvenida a los nuevos
participantes de la competencia.
Te dejo el enlace para expectadores para que puedas ver la emision:
http://youtu.be/qkkK10cOxc0

Mi canal de skype estará abierto para que puedas hacer preguntas:
skype: romulo.groenke1
e-mail: AUC2016@bitdubai.org

Te esperamos, hay mucho por descubrir !

**Comment by rjgroenke** [comment]
@Arturoz30 
Buen dia 
Debido a tu interes inicial en participar en el proyecto, hemos insistido en el llamado a tu atencion en continuar tu proceso de registro, firma y adopcion del componente. Si ya no puedes o no quieres participar, haznolo saber, ya que tu lugar lo puede ocupar otra persona que si tenga el interes real de hacerlo.

Por lo tanto, una vez mas, te invitamos para el pŕoximo lunes 22-2-2016 a las 19 Hs ARG ( GMT-3)
 al cuarto hang-out de bienvenida a los nuevos participantes.

https://hangouts.google.com/call/7ek3ar36ie472y7ofmgdmhx7xqa

 Te dejo el enlace para participar como expectadores:

 http://youtu.be/0ksUl-zDD34 [2]

 Para que puedas participar con tus comentarios y consultas, estaré
moderando el siguiente canal de skype:

 https://join.skype.com/qopkPzDX4QZN [3]

 Te esperamos para que seas parte de Fermat, el proyecto open source en
tecnología blockchain con más rapido crecimiento!!

 Hay muchas formas de participar!
 Visitá: www.fermat.org [4]

 Saludos y que tengas un excelente dia,

 Romulo Groenke.
 *Compettion Manager*
 *FERMAT.ORG *
 (AUC2016@bitdubai.com)

**Comment by gustl-arg** [comment]
Participant never showed up again!
