### ISSUE TITLE
AUC 2016 Test-Platform Layer-Name Component-Test

### ISSUE THREAD

**Issue by Chofo7** [Fermat-ORG/competition#29]
Estimados @competition-team,

Deseo solicitar en adopción el componente mencionado en el título cuyo autor es @Author-User-Name de acuerdo al concurso Adoptá un Componente.

Saludos,

<Gustavo Adolfo Blanco>

**Comment by gustl-arg** [comment]
Por favor @rjgroenke establece contacto con le participante y guialo.

**Comment by rjgroenke** [comment]
@Chofo7 Buenas noches Gustavo Blanco. Es necesario pasar por el paso 3 del link "Adopta un Componente" para llegar al paso de adopcion como tal del mismo. Te sugiero completar el paso 3 y luego fijate bien en el paso 7 y completarlo luego

**Comment by gustl-arg** [comment]
@Chofo7 abandoned the competition 20-2-2016, noticed @rjgroenke via e-mail .
